name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: 'latest'
        auto-activate-base: false  # We handle activation manually

    - name: Create Conda environment
      run: |
        # Find Conda installation path
        echo "Conda installation path: $CONDA"
        ls $CONDA/etc/profile.d/  # Check available files
        conda env create --file .github/workflows/environment.yml --name myenv

    - name: Install additional dependencies
      run: |
        # Adjust the path if needed based on the output from previous step
        source $CONDA/etc/profile.d/conda.sh
        conda activate myenv
        conda install numpy pandas matplotlib scipy scikit-learn flake8 pytest

    - name: Lint with flake8
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate myenv
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate myenv
        pytest
